// Code generated by protoc-gen-go.
// source: auth_service.proto
// DO NOT EDIT!

/*
Package auth_service is a generated protocol buffer package.

It is generated from these files:
	auth_service.proto

It has these top-level messages:
	AuthRequest
	AuthResponse
*/
package auth_service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import account_service "github.com/lileio/account_service"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthRequest struct {
	Email    string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *AuthRequest) Reset()                    { *m = AuthRequest{} }
func (m *AuthRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()               {}
func (*AuthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AuthRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthResponse struct {
	Token   string                   `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Account *account_service.Account `protobuf:"bytes,2,opt,name=account" json:"account,omitempty"`
}

func (m *AuthResponse) Reset()                    { *m = AuthResponse{} }
func (m *AuthResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()               {}
func (*AuthResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AuthResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthResponse) GetAccount() *account_service.Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func init() {
	proto.RegisterType((*AuthRequest)(nil), "auth_service.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "auth_service.AuthResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AuthService service

type AuthServiceClient interface {
	Authenticate(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Authenticate(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := grpc.Invoke(ctx, "/auth_service.AuthService/Authenticate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AuthService service

type AuthServiceServer interface {
	Authenticate(context.Context, *AuthRequest) (*AuthResponse, error)
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth_service.AuthService/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Authenticate(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth_service.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _AuthService_Authenticate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth_service.proto",
}

func init() { proto.RegisterFile("auth_service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x3f, 0x4b, 0xc5, 0x30,
	0x14, 0xc5, 0x7d, 0x82, 0xff, 0xf2, 0xde, 0x14, 0x1c, 0x6a, 0x06, 0x79, 0x74, 0x72, 0x4a, 0xa1,
	0x0e, 0x8e, 0x52, 0x17, 0xf7, 0x0a, 0x22, 0x2e, 0x92, 0xc6, 0x8b, 0x0d, 0xb6, 0xb9, 0xb5, 0xb9,
	0xd1, 0xaf, 0x2f, 0xe6, 0x5a, 0xa9, 0xa5, 0xe3, 0xc9, 0xb9, 0xf9, 0xdd, 0x73, 0x8f, 0x90, 0x26,
	0x52, 0xfb, 0x12, 0x60, 0xfc, 0x74, 0x16, 0xf4, 0x30, 0x22, 0xa1, 0xdc, 0xcd, 0xdf, 0xd4, 0xcd,
	0x9b, 0xa3, 0x36, 0x36, 0xda, 0x62, 0x5f, 0x74, 0xae, 0x03, 0x87, 0x85, 0xb1, 0x16, 0xa3, 0xa7,
	0x69, 0x64, 0xa9, 0x19, 0x93, 0xdf, 0x8a, 0x6d, 0x15, 0xa9, 0xad, 0xe1, 0x23, 0x42, 0x20, 0x79,
	0x2e, 0x8e, 0xa0, 0x37, 0xae, 0xcb, 0x36, 0xfb, 0xcd, 0xd5, 0x59, 0xcd, 0x42, 0x2a, 0x71, 0x3a,
	0x98, 0x10, 0xbe, 0x70, 0x7c, 0xcd, 0x0e, 0x93, 0xf1, 0xa7, 0xf3, 0x27, 0xb1, 0x63, 0x40, 0x18,
	0xd0, 0x07, 0xf8, 0x21, 0x10, 0xbe, 0x83, 0x9f, 0x08, 0x49, 0xc8, 0x52, 0x9c, 0xfc, 0xee, 0x4f,
	0x80, 0x6d, 0x99, 0xe9, 0x65, 0x9e, 0x8a, 0x75, 0x3d, 0x0d, 0x96, 0x8f, 0x1c, 0xed, 0x81, 0x7d,
	0x79, 0xcf, 0x8b, 0xc0, 0x93, 0xb3, 0x86, 0x40, 0x5e, 0xe8, 0x7f, 0xad, 0xcc, 0xae, 0x50, 0x6a,
	0xcd, 0xe2, 0x7c, 0xf9, 0xc1, 0xdd, 0xfe, 0xf9, 0x72, 0xa5, 0xad, 0xd9, 0x87, 0xe6, 0x38, 0x75,
	0x73, 0xfd, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x3a, 0xf8, 0x32, 0x63, 0x78, 0x01, 0x00, 0x00,
}
